name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt update
        sudo apt install -y unzip wget
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip commandlinetools-linux-8512546_latest.zip
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --update
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Set up Buildozer
      run: |
        pip install --upgrade buildozer
        buildozer --version

    - name: Build with Buildozer
      run: buildozer android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: .buildozer/android/platform/build-arm64-v8a_armeabi-v7a
    - name: List SDK directory contents
      run: ls -la $HOME/android-sdk

    - name: Check JAVA_HOME
      run: echo $JAVA_HOME

    
