name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Buildozer and Python-for-Android
        run: |
          pip install --upgrade buildozer python-for-android

      - name: Clean Buildozer and python-for-android Cache
        run: |
          rm -rf /home/runner/.buildozer
          rm -rf /home/runner/work/main/main/.buildozer

      - name: List Buildozer Directory (Before Build)
        run: |
          echo "Listing parent directories:"
          ls -al /home/runner/work/main/main/.buildozer/android
          echo "Listing full path:"
          ls -al /home/runner/work/main/main/.buildozer

      - name: Build with Buildozer
        run: |
          buildozer android clean
          buildozer android debug

      - name: List Buildozer Directory (After Build)
        run: |
          echo "Listing directory after build:"
          ls -al /home/runner/work/main/main/.buildozer/android/platform || echo "Directory does not exist"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/
